In [1]:
from ml_enhance import QuantumFPFileLoader, QFPFeatureEngineer, ConformerAggregator, QuantumFPDatasetBuilder, RDKitFeatureCalculator
from pathlib import Path
from rdkit import Chem
import pandas as pd
import numpy as np
import json
import os

In [2]:
OUTPUT_PATH = Path("../data/QuantumFP/QFP_output")

loader = QuantumFPFileLoader(OUTPUT_PATH)
output_files = loader.list_output_files()
output_files_numbers: list[Path] = [int(path.name.split('.')[0].split('_')[-1]) for path in output_files]

In [3]:
print(output_files)

[WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_0.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_10.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_100.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1000.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1001.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1002.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1003.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1004.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1005.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1006.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1007.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1008.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1009.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_101.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1010.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1011.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1012.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1013.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1014.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1015.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1016.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1017.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1018.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1019.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_102.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1020.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1021.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1022.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1023.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1024.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1025.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1026.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1027.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1028.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1029.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_103.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1030.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1031.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1032.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1033.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1034.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1035.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1036.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1037.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1038.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1039.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_104.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1040.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1041.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1042.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1043.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1044.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1045.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1046.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1047.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1048.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1049.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_105.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1050.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1051.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1052.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1053.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1054.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1055.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1056.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1057.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1058.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1059.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_106.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1060.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1061.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1062.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1063.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1064.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1065.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1066.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1067.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1068.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1069.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_107.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1070.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1071.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1072.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1073.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1074.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1075.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1076.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1077.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1078.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1079.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_108.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1080.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1081.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1082.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1083.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1084.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1085.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1086.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1087.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1088.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1089.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_109.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1090.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1091.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1092.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1093.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1094.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1095.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1096.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1097.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1098.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1099.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_11.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_110.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1100.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1101.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1102.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1103.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1104.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1105.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1106.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1107.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1108.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1109.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_111.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1110.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1111.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1112.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1113.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1114.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1115.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1116.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1117.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1118.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1119.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_112.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1120.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1121.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1122.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1123.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1124.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1125.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1126.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1127.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1128.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1129.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_113.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1130.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1131.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1132.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1133.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1134.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1135.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1136.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1137.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1138.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1139.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_114.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1140.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1141.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1142.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1143.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1144.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1145.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1146.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1147.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1148.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1149.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_115.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1150.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1151.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1152.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1153.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1154.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1155.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1156.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1157.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1158.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1159.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_116.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1160.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1161.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1162.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1163.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1164.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1165.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1166.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1167.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1168.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1169.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_117.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1170.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1171.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1172.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1173.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1174.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1175.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1176.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1177.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1178.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1179.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_118.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1180.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1181.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1182.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1183.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1184.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1185.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1186.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1187.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1188.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1189.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_119.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1190.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1191.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1192.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1193.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1194.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1195.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1196.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1197.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1198.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1199.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_12.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_120.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1200.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1201.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1202.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1203.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1204.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1205.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1206.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1207.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1208.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1209.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_121.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1210.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1211.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1212.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1213.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1214.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1215.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1216.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1217.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1218.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1219.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_122.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1220.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1221.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1222.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1223.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1224.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1225.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1227.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1228.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1229.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_123.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1230.json.gz'), WindowsPath('../data/QuantumFP/QFP_output/internship_smiles2_1231.json.gz'), WindowsPath('..

In [4]:
# builder = QuantumFPDatasetBuilder(OUTPUT_PATH)
# df, errors = builder.build_dataset(multiprocess=True)

In [5]:
df = pd.read_json('../data/temp_df.json', orient='split', compression='infer')

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 8837 entries, 0 to 8836
Data columns (total 56 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   smiles                                       8837 non-null   str
 1   energy                                       8802 non-null   float64
 2   atomization_energy                           8802 non-null   float64
 3   homo_lumo_gap                                8802 non-null   float64
 4   ionization_energy                            8802 non-null   float64
 5   electron_affinity                            8802 non-null   float64
 6   chemical_potential                           8802 non-null   float64
 7   molecular_dipole_norm                        8802 non-null   float64
 8   molecular_quadrupole_principal_invariant_2   8802 non-null   float64
 9   molecular_quadrupole_principal_invariant_3   8802 non-null   float64
 10  molecular_polarizability_mean                8802 non-null   float64
 11  molecular_polarizability_anisotropy          8802 non-null   float64
 12  enthalpy                                     8802 non-null   float64
 13  zero_point_energy                            8802 non-null   float64
 14  radius_of_gyration                           8802 non-null   float64
 15  molecular_volume                             8802 non-null   float64
 16  sterimol_L                                   8802 non-null   float64
 17  sterimol_Bmin                                8798 non-null   float64
 18  sterimol_Bmax                                8798 non-null   float64
 19  molecular_sasa                               8802 non-null   float64
 20  solvation_energy_water                       8802 non-null   float64
 21  solvation_energy_thf                         8802 non-null   float64
 22  solvation_energy_cyclohexane                 8802 non-null   float64
 23  solvation_energy_dmso                        8802 non-null   float64
 24  gibbs_free_energy_300K                       8802 non-null   float64
 25  entropy_300K                                 8802 non-null   float64
 26  heat_capacity_300K                           8802 non-null   float64
 27  ir_centroid_freq_1500                        8802 non-null   float64
 28  ir_norm_intensity_1500                       8802 non-null   float64
 29  ir_centroid_freq_1500_2750                   8802 non-null   float64
 30  ir_norm_intensity_1500_2750                  8802 non-null   float64
 31  ir_centroid_freq_2750_4000                   8802 non-null   float64
 32  ir_norm_intensity_2750_4000                  8802 non-null   float64
 33  avg_effective_coordination_number            8802 non-null   float64
 34  avg_atomic_polarizability_mean               8802 non-null   float64
 35  avg_partial_charge_water                     8802 non-null   float64
 36  avg_percentage_buried_volume                 8802 non-null   float64
 37  avg_atomic_polarizability_anisotropy         8802 non-null   float64
 38  avg_atomic_sasa                              8802 non-null   float64
 39  avg_partial_charge_thf                       8802 non-null   float64
 40  avg_atomic_quadrupole_principal_invariant_2  8802 non-null   float64
 41  avg_partial_charge_cyclohexane               8802 non-null   float64
 42  avg_partial_charge_dmso                      8802 non-null   float64
 43  avg_atomic_fukui_minus                       8802 non-null   float64
 44  avg_atomic_quadrupole_principal_invariant_3  8802 non-null   float64
 45  avg_atomic_fukui_plus                        8802 non-null   float64
 46  avg_partial_charge                           8802 non-null   float64
 47  avg_atomic_dipole_norm                       8802 non-null   float64
 48  avg_atomic_charge_dipole_interaction         8802 non-null   float64
 49  avg_bond_stiffness                           8802 non-null   float64
 50  avg_overlap_integral                         8802 non-null   float64
 51  avg_bond_length                              8802 non-null   float64
 52  avg_atomic_dipole_dipole_interaction         8802 non-null   float64
 53  avg_nuclear_repulsion                        8802 non-null   float64
 54  avg_atomic_charge_quadrupole_interaction     8802 non-null   float64
 55  avg_bond_energy                              8660 non-null   float64
dtypes: float64(55), str(1)
memory usage: 3.8 MB

In [7]:
df["sterimol_Bmax"].to_list()

[5.2549684348,
 3.9595541428,
 4.4360733656,
 4.793257362,
 6.1256587148,
 6.29774399,
 4.8100473134,
 6.3564550272,
 5.2518393449,
 11.86262292,
 5.0792114122,
 4.7045870618,
 6.8048438193,
 5.8587499313,
 10.8269028928,
 4.8864851556,
 5.9725200575,
 4.5967830747,
 5.7324031741,
 8.691689995,
 9.8201800529,
 4.3853416268,
 4.9469555557,
 4.5719543809,
 5.3866938148,
 4.0627224569,
 6.2352985946,
 8.6658057149,
 6.4716246706,
 4.9151133483,
 9.0941090057,
 4.3870715462,
 4.6603705633,
 4.4100004645,
 4.6441328752,
 5.9434760281,
 5.1394050901,
 7.465449549,
 4.2990605962,
 4.5653744534000005,
 7.2272078774,
 5.0787288267,
 4.4379160491,
 5.0527038669,
 7.1800193071,
 5.4038423467,
 5.2376922683,
 4.4741636521,
 4.5978247075,
 5.5658949131,
 5.5113058008,
 11.1814398819,
 8.9934952264,
 7.8344778665,
 6.1062447341,
 3.580910169,
 7.3690720885,
 9.0868252252,
 4.6195781225,
 5.7273386523,
 5.3923588819,
 10.3729125268,
 4.7945604287,
 4.8589533566,
 5.6001188213,
 6.2482014849,
 4.9982981717,
 5.9417091334,
 7.3311187417,
 2.31,
 7.7638034969,
 5.5664957101,
 4.7856183583,
 6.6596892526,
 8.0179879655,
 5.2709018135,
 6.812072044,
 4.9767893139,
 4.4419879366,
 5.7081569303,
 4.1049416804,
 6.8227932692,
 6.0395648493,
 5.8987702473,
 5.7280907094,
 18.5791392191,
 5.9478297457,
 8.2052579711,
 5.6674390757,
 8.519871019,
 7.317795322,
 6.521050467,
 5.8070522387,
 6.7575042955,
 10.7863645026,
 3.7495467793,
 12.5777160687,
 8.9781909688,
 5.6329814056,
 5.3508990043,
 5.5795547497,
 7.4289801277,
 5.101560182,
 3.9091094876,
 4.7770537889,
 3.3284132362,
 5.5829403630000005,
 4.686936935,
 3.5506779865,
 9.479200895,
 7.3674521377,
 4.0817555919,
 3.6788427436999998,
 4.5597894072,
 4.5996007289000005,
 5.0858837709,
 7.3055553376999995,
 6.173545006,
 5.2872065388,
 5.0911391674,
 5.098903564,
 nan,
 5.0032172776,
 5.1942781786,
 6.7791823471,
 4.789022089,
 4.2465737807,
 4.8222251634,
 5.4067318757,
 3.8688121921,
 3.7493702723,
 3.6352354674000003,
 nan,
 8.0604996958,
 6.9809657558,
 9.8915068115,
 3.8458776094,
 6.0404690643,
 4.011224918,
 3.9009834357,
 6.3188836703,
 11.2486582811,
 7.972260584,
 4.797580386,
 7.2751477201,
 4.9314510785,
 11.7791599948,
 4.0110480578,
 5.2710038588,
 5.5501971718,
 10.4366728919,
 5.8077105413000005,
 7.7720203615,
 7.2917612774,
 8.7142698732,
 5.878125902,
 4.8853036932,
 5.2953069314,
 5.9028812048,
 4.433465221,
 4.9063822972,
 7.7938448287,
 6.4645422923,
 5.3574542069,
 8.7131399849,
 7.7093311289,
 3.2012950264,
 7.3214599913,
 5.2124664334,
 3.9796039087,
 7.7956279934,
 7.7495032242,
 6.6429371369,
 6.7943274027000005,
 7.807420019,
 6.3013587441,
 5.7246206607,
 7.0443782144,
 3.9451580746,
 3.8771751299,
 6.3206367712,
 8.4681724151,
 4.9333128069,
 4.5642397844,
 7.0348969434,
 4.2410240477,
 4.6882918883,
 9.3403017718,
 nan,
 7.1956766206000005,
 4.0883975224,
 6.9674449699,
 4.3247699577,
 8.4604103982,
 7.6602562597,
 4.002279545,
 5.7112413168,
 5.7522353913,
 7.5822175291,
 6.6113375142,
 7.9083379648,
 4.8329886893000005,
 5.0746634742,
 7.1329410596,
 5.191965291,
 4.3262651476,
 5.8773082055,
 3.0591842615,
 6.0975043537,
 5.5652267366,
 7.9539992915,
 7.221267949,
 6.2294668512,
 5.7118682955,
 6.1359121687,
 7.458808093,
 7.2150301156,
 7.3130376502,
 6.1028322391,
 6.1980520135,
 7.5683692015,
 10.4874217756,
 nan,
 7.0885890152,
 5.6496030018,
 6.2966390558,
 5.3878985822,
 5.6355733617,
 11.499197794,
 11.5373280396,
 8.1912412983,
 6.2166858888,
 9.6163205683,
 5.409428926,
 10.5215143074,
 6.2302649164,
 6.9243852703,
 5.9883292528,
 5.4818082723,
 5.4224714421,
 7.5057961856,
 4.4101892272,
 5.2841817068,
 8.2889012821,
 9.4907252668,
 nan,
 8.0568173329,
 6.7244706592,
 4.4665573431,
 5.6565632427,
 9.2487694915,
 8.1798548888,
 7.4550121245,
 7.4773090342,
 6.3193012715,
 9.1625638188,
 7.0731463476,
 4.9096162153,
 7.5986236553,
 8.2761232148,
 5.8097962604,
 6.9489262655,
 7.7375746693,
 5.2749055281,
 6.976200865,
 10.1840260916,
 6.9664750925,
 13.5601784237,
 3.0061805315,
 8.1328792885,
 8.0559491077,
 7.5219776675,
 11.0060533855,
 7.1582878308,
 nan,
 4.8885620707,
 6.1205778619,
 12.4930978866,
 9.2534001049,
 7.1277049573,
 7.2480620085,
 7.2434580485,
 7.5455021937,
 5.6939208086,
 6.6277179818,
 7.4483875179,
 5.0817325323,
 7.0468545326,
 5.4982630528,
 nan,
 4.8000096024,
 5.6428245807,
 8.821944394700001,
 6.4284774986,
 8.83573567,
 5.2897587549,
 8.4802545539,
 6.6609192152,
 13.9629243096,
 5.0156871939,
 5.1273853732,
 4.5112080822,
 6.5912893477,
 8.4505802268,
 nan,
 7.3764687217,
 nan,
 9.619619631,
 nan,
 9.7117519301,
 nan,
 6.4580169735,
 4.3969955768,
 nan,
 11.691377922200001,
 nan,
 7.1913557313,
 9.8156020451,
 7.1660463451,
 nan,
 8.2167989612,
 5.001165315,
 7.5429375693,
 3.4198988103,
 9.3317696173,
 nan,
 nan,
 10.7461169865,
 5.4825237596,
 5.6506412053,
 6.2459090759,
 7.6864734357,
 10.291874571,
 7.7094225007,
 4.664251015,
 5.9766756086,
 nan,
 9.7159490579,
 7.2793224963,
 6.0822675959,
 5.5798411437,
 nan,
 9.0085392225,
 6.1144471936,
 8.231810614,
 11.6852387961,
 5.2577611954,
 8.6532888888,
 9.0707318456,
 6.7221518290999995,
 5.0084354909,
 10.8133961582,
 6.6828214209,
 5.9156922036,
 8.762069813,
 7.1101391559,
 8.1433523591,
 4.8229133326,
 8.0811633602,
 7.8732793295,
 6.8297449961000005,
 6.8510520432,
 9.6247499036,
 4.6083625383,
 6.3620928587,
 6.712458338,
 7.3561770029,
 8.0713949365,
 5.0070400103,
 5.1182871149,
 8.2837790878,
 5.376700304,
 nan,
 8.3976583949,
 9.6376958183,
 8.0628170474,
 7.7015588681,
 5.2261852398,
 9.8946773365,
 5.1830491562,
 6.8300411966,
 7.6771654844,
 9.0531068366,
 1.92,
 nan,
 6.2771074423,
 6.0970856754,
 4.9110772735,
 8.0427656917,
 8.3337085751,
 5.8907264262000005,
 5.9984237904,
 6.6871685366,
 9.2103575393,
 9.9733903026,
 10.0143928685,
 nan,
 9.144228486,
 6.077236886,
 3.202927074,
 4.4294859465,
 4.2615763384,
 3.3413980883,
 3.4096254976,
 3.6926764993,
 3.2220450229,
 4.5320849518,
 4.0001857553,
 3.7513751631,
 4.0659695194,
 5.646305684,
 4.5945958793,
 5.229081665,
 4.043655673,
 3.5661312385,
 4.8862827182,
 7.4722383519,
 4.9377566425,
 4.8713488937000005,
 3.2087453829,
 7.3715418152,
 4.7662130334,
 7.432878629,
 4.0155676442,
 6.4092652202,
 3.607874847,
 4.4675030315,
 4.9366905115,
 4.5408878033,
 4.5585540846,
 3.3682571287,
 4.6505409165,
 4.5383872445,
 4.6165783043,
 5.1599190457,
 4.304214816,
 5.8530930686,
 6.2180327039,
 4.4514169701,
 5.0541087156,
 4.9917008902,
 nan,
 3.7774254867,
 3.9813138028,
 3.5459007852999997,
 4.8779231957,
 3.5479368105,
 4.1920963398,
 4.2660108511,
 4.7035092483,
 3.6525580277,
 3.9036100195000003,
 4.6891111905,
 3.2535788059,
 3.5788673136,
 3.2400782439,
 3.0843551984,
 3.2712016892999998,
 3.7097037314,
 6.5962633244,
 5.911441626,
 7.7065943491999995,
 5.0976342827,
 3.6335040267,
 4.0390806059,
 4.8495261003,
 5.23264933,
 4.5079066417,
 5.648839826,
 4.4587101276,
 4.075491178,
 5.2092782629,
 7.2232106585,
 5.7706864255,
 5.9529159886,
 7.8078212266,
 6.9099919335,
 10.4524868431,
 4.2677579967,
 4.7786639858,
 4.6814409268,
 5.1169680956,
 4.1575214808,
 4.8831959194,
 3.8538747337,
 3.8542060276,
 3.5479014041,
 6.006530368,
 4.0247480754,
 3.5071318695,
 8.9341479055,
 4.0038490444,
 3.3430626376,
 4.4869617995,
 5.5081109194,
 5.4330126106,
 3.1153677413,
 4.2251802047,
 3.8996885373,
 3.5895939998,
 3.1699392755,
 4.2320955399,
 3.5135868863,
 4.1250144873,
 3.4927207729,
 4.2598832761,
 3.7128187993,
 5.7606987172,
 8.1353058639,
 3.9489526073,
 4.0045417331,
 5.2285183386,
 6.250819687,
 2.2283877425,
 4.005335888,
 5.1244145067,
 4.2673812514,
 5.1922539855,
 5.1037467447000004,
 4.3170280753,
 3.9539603519,
 5.2690425283,
 3.8835403921,
 4.770656755,
 4.2632183507,
 4.1503744454,
 6.6231621013,
 4.8417838966,
 4.5125316475,
 2.8621578867,
 3.6737710286,
 3.7782466515,
 3.2929027042,
 2.2327198868,
 4.755619987,
 4.8375018589,
 3.6257057349,
 3.3393410426,
 3.3851200791,
 3.9727098691,
 5.7885712338,
 3.3517285998,
 4.3579992668,
 5.2584575671,
 4.1359455028,
 8.9670924882,
 3.3970289081000002,
 7.6576770521,
 4.4221183803,
 2.8936513899,
 6.1710727156,
 4.8617145215,
 4.6784332315,
 3.2950013202,
 3.7918306836999998,
 4.1089032306,
 6.2933453255,
 8.9334293024,
 3.4011551535,
 4.3538734021,
 3.5003079273,
 5.0245893962,
 3.7781874326000002,
 4.5895798824,
 4.289079956,
 3.9095862349,
 9.840044665,
 3.495987307,
 5.904348666,
 3.7402922814,
 3.8117846801,
 3.9006912765,
 4.8188002248,
 5.5027566384,
 3.6677107966999998,
 5.6033090422,
 5.9659915681,
 3.0933691206,
 3.8140864503,
 4.2228957054,
 5.2970702557,
 4.6231245519,
 4.2239237491,
 2.49,
 5.1988498469,
 2.7176233184000003,
 3.9548316811,
 3.7348014593,
 4.8647984617,
 3.5496136144,
 8.3922591117,
 5.8431164209,
 3.9341071916,
 5.3937345026,
 5.2466498292,
 3.555437499,
 7.993743157,
 4.5315196074,
 4.6538150659,
 3.7329313223,
 8.5611736757,
 5.2539996359,
 5.3327344357,
 4.3573035366,
 3.4641058311,
 4.8675529089000005,
 5.1090280167,
 3.8575939516,
 3.8061135861,
 3.9809045717,
 4.3111680792,
 4.8048595968,
 2.9232781279,
 3.9071812207,
 3.3833002739999998,
 4.8129206603,
 4.599600322,
 3.8473339619,
 4.3016890987,
 7.3546116054,
 3.8106887685,
 3.2237128377,
 3.5897161476,
 3.9957139167999998,
 3.4410498131000002,
 2.9957893557,
 4.9728647016,
 4.5625490573,
 4.4567149855,
 4.1299528265,
 4.3654664077,
 4.3643596711,
 4.4312801721,
 4.4534333867,
 4.3032680875,
 5.6376186973,
 4.4697372673,
 3.8871515186,
 5.9044672827,
 3.8558493496,
 3.6379613434999998,
 3.9188661143,
 4.9100995495,
 4.7750189423,
 5.6335239528,
 5.0703872798,
 4.7635545836,
 4.5602161849,
 6.8975154801,
 4.3625754471,
 4.2564065005,
 4.4421379041,
 3.5735908654,
 4.7033524234,
 3.8583116243,
 8.4967445891,
 4.3849353689,
 6.366210366,
 3.2527187044,
 3.69045303,
 3.2687123347,
 3.9510509047999998,
 3.9327667257,
 4.2544598845,
 4.3411329504000005,
 5.0375289415,
 4.4635365551,
 4.5289457161,
 4.2287114837,
 4.5245538276,
 4.1451193181,
 3.8510524675,
 4.5660325786,
 3.8764790548,
 2.972783636,
 6.1858290834,
 4.2388367056,
 4.9082360003000005,
 5.8828781131,
 4.5758961344,
 5.3695322589,
 5.0090148184,
 4.2649171261,
 4.2632183507,
 4.7339612547000005,
 6.8183116049,
 4.4790604117,
 3.7353638366,
 4.7161111462,
 3.3858486669,
 4.2712038546,
 4.3485563091,
 3.7840485299,
 4.4658725740000005,
 4.9607767765,
 6.977086797,
 4.0638781325,
 6.585330866,
 2.9726783705,
 7.004410037,
 4.3259395183,
 4.4495856014,
 3.450626617,
 4.9985098509,
 4.4335701191,
 4.5596814734,
 4.4125713921,
 4.4826459427,
 3.8544723071,
 5.0735804678,
 4.1796199892,
 2.2680826347,
 4.0373931081,
 5.3634553724,
 4.1435106019,
 4.8052565828,
 3.561971374,
 3.3362084434,
 4.6996631035,
 4.5334838752,
 4.4429846518,
 3.5898514934,
 5.2913421592,
 3.8944053412,
 4.9132543097,
 4.4765612229,
 6.36696314,
 3.6182659792000003,
 3.2329528446,
 4.9642892179,
 4.2880534088,
 4.234310478,
 5.6916371735,
 4.9954572828,
 3.6483569786,
 4.3971039862,
 4.8334693573,
 4.0522408427,
 5.4559994451,
 4.7369356718999995,
 5.2738358892,
 5.9761850369000005,
 4.9351440844,
 4.389560867,
 4.2950291434,
 5.7994751798,
 4.0922047046,
 4.474311763,
 5.4790033706,
 7.6309075752,
 4.264098598,
 5.6415020359,
 3.838171099,
 4.2333383339,
 4.5693561267,
 4.3265124755,
 7.2096955483,
 5.6164268904,
 5.2680907076,
 4.2344009352,
 4.0642104319,
 4.4444276262,
 3.2720960742000003,
 4.0614063019,
 5.2487630945,
 4.2546250806,
 4.4099467195,
 5.0103484556,
 3.337626994,
 4.6694476886,
 3.4226232354,
 3.2426144463,
 6.0428688911,
 4.1667688988,
 4.973907864,
 3.6248891755,
 4.441990104,
 4.5150377291,
 5.3471874005,
 3.9081425634,
 3.8761927132,
 5.0129642065,
 5.4252932748,
 4.6089813766,
 3.3699077955,
 2.8058948728,
 3.9896870702,
 4.0597775316,
 6.0731030525,
 3.3744486168,
 4.1988414564,
 4.2997385551,
 4.8646933824000005,
 3.8237698706,
 3.3731884944,
 5.2101563389,
 4.3305231995,
 4.1608627729,
 3.6552081385,
 5.4399515341,
 3.8925361439,
 4.8754069219,
 4.7153994127,
 2.8490840661,
 3.7809330636,
 5.0480785041,
 2.5235498934000002,
 3.3417358424,
 3.9081870037,
 4.4585166288,
 8.6397515116,
 3.9827982477,
 4.2760596347,
 3.21129728,
 5.4244482368,
 3.8426139123,
 4.9391813904,
 3.0600518154,
 3.8250760312,
 5.6697331807,
 4.7403307508,
 2.9831552453,
 6.1321668536,
 3.5249461336,
 3.5407163179,
 3.9983606867,
 4.4678109442,
 3.853910234,
 4.8224198426000005,
 3.9798627436,
 3.5963691607,
 8.4689202583,
 4.4690340768,
 4.7686857345,
 4.8238118212,
 4.5049907676,
 6.0899969724,
 3.3370639338,
 4.4508721831999996,
 5.174008173,
 4.3427271578,
 4.2906033252,
 5.8318491691,
 5.1178319117,
 3.4990933632,
 4.9706280346,
 4.0122228585,
 4.4815685188,
 4.8743602472,
 4.5117365175,
 4.7960493237,
 4.6327768254,
 5.5423584133,
 4.0550200913,
 4.8508716288,
 4.2137386485,
 7.1118099937,
 4.8625181575,
 3.9386971920000002,
 4.8594134818,
 3.7607212922,
 5.0492363405,
 4.2197074924,
 4.8468515866,
 5.0328294372,
 5.4504873609,
 4.73684026,
 6.8247940137,
 5.0580211486,
 3.7584668175,
 4.2482102843,
 4.0523068224,
 5.5130623246,
 3.9291241934,
 4.770270566,
 4.5428853088,
 4.1905318181,
 4.2376114684,
 5.0661925873,
 4.1223753179,
 7.5342821314,
 2.6722831927,
 6.6796739995,
 3.3624221544,
 3.215875305,
 3.9751909552,
 5.2448847572,
 5.277476547,
 8.4226059165,
 4.6179662561,
 4.5075010897,
 4.9862635436,
 4.6240157329,
 3.7955465449,
 3.3785034835,
 3.4429925609,
 4.3537344893,
 4.7765634888,
 2.7059761877,
 3.2856599825,
 4.2462490172,
 4.6875888071,
 5.5773723517,
 3.8303189328,
 4.9945201945,
 6.7919555536,
 4.2512645264,
 3.0699636485,
 4.8781609386,
 3.9017070324,
 5.5113335317,
 3.9808396349,
 6.1576986116,
 4.5651217049,
 5.6339832895,
 4.2584996333,
 3.9852817411,
 3.8321143966999998,
 4.4401269253,
 7.001532851,
 3.8529258458,
 4.5230126994,
 3.8560816352,
 3.6308751373,
 3.7861215523,
 4.4265696911,
 4.0119638545,
 4.0211402192,
 4.8515465011,
 4.3505644693,
 3.3216974779,
 4.3017876258,
 3.7891974629,
 4.6215712261,
 5.7091352929,
 3.8674979934,
 5.1492042732,
 4.1372364919,
 5.2620116553,
 5.4574702855,
 3.610974709,
 4.7254689363,
 3.654472025,
 5.3272970508,
 6.3924971019,
 4.0051343638,
 6.3356167229,
 4.0504634121,
 3.4845976739,
 4.7676184841,
 3.6292286575,
 5.0034302186,
 5.6546886619,
 5.0792719728,
 5.9020333169,
 8.8586204248,
 3.7757783322,
 3.8180390977,
 4.9947669418,
 5.5014728154,
 4.2542416877,
 3.8198133754,
 4.8354339726,
 3.9188309684,
 5.3641931628,
 5.1949923298,
 3.6664621084,
 4.4567087395,
 5.485193636,
 3.9979145099,
 3.7696468707,
 4.9420112185,
 3.7861230867,
 5.466962999,
 3.6651379311000003,
 3.7247192813,
 2.02,
 3.4121458275,
 4.7105943805,
 3.9555736273,
 3.3742109686,
 3.3445630229,
 4.0975802797,
 3.2594979721,
 3.6533734337,
 3.5417232304,
 4.4800519171,
 4.9158048329,
 3.6543834134,
 4.4949442587,
 4.0912202318,
 5.9030612491,
 3.1767291236,
 3.6703903168,
 3.8105864978,
 3.9123755699,
 4.2215114042,
 3.9220573954,
 5.0088024772,
 7.6958015799,
 ...]

In [8]:
# df.to_json('../data/temp_df.json', orient='split', compression='infer', index=True)

In [9]:
df[df["smiles"]=="[F:1][C:2]([F:3])([F:4])[F:5]"]

,smiles,energy,atomization_energy,homo_lumo_gap,ionization_energy,electron_affinity,chemical_potential,molecular_dipole_norm,molecular_quadrupole_principal_invariant_2,molecular_quadrupole_principal_invariant_3,...,avg_partial_charge,avg_atomic_dipole_norm,avg_atomic_charge_dipole_interaction,avg_bond_stiffness,avg_overlap_integral,avg_bond_length,avg_atomic_dipole_dipole_interaction,avg_nuclear_repulsion,avg_atomic_charge_quadrupole_interaction,avg_bond_energy
105,[F:1][C:2]([F:3])([F:4])[F:5],-21.078563,0.803077,0.66204,0.74286,-0.235545,-0.259115,0.000124,-1.810000e-08,0.0,...,0.0,0.240626,0.01759,0.671279,0.141857,2.483285,0.009155,10.944868,0.005217,NaN

In [10]:
df.isnull().sum()

smiles                                           0
energy                                          35
atomization_energy                              35
homo_lumo_gap                                   35
ionization_energy                               35
electron_affinity                               35
chemical_potential                              35
molecular_dipole_norm                           35
molecular_quadrupole_principal_invariant_2      35
molecular_quadrupole_principal_invariant_3      35
molecular_polarizability_mean                   35
molecular_polarizability_anisotropy             35
enthalpy                                        35
zero_point_energy                               35
radius_of_gyration                              35
molecular_volume                                35
sterimol_L                                      35
sterimol_Bmin                                   39
sterimol_Bmax                                   39
molecular_sasa                                  35
solvation_energy_water                          35
solvation_energy_thf                            35
solvation_energy_cyclohexane                    35
solvation_energy_dmso                           35
gibbs_free_energy_300K                          35
entropy_300K                                    35
heat_capacity_300K                              35
ir_centroid_freq_1500                           35
ir_norm_intensity_1500                          35
ir_centroid_freq_1500_2750                      35
ir_norm_intensity_1500_2750                     35
ir_centroid_freq_2750_4000                      35
ir_norm_intensity_2750_4000                     35
avg_effective_coordination_number               35
avg_atomic_polarizability_mean                  35
avg_partial_charge_water                        35
avg_percentage_buried_volume                    35
avg_atomic_polarizability_anisotropy            35
avg_atomic_sasa                                 35
avg_partial_charge_thf                          35
avg_atomic_quadrupole_principal_invariant_2     35
avg_partial_charge_cyclohexane                  35
avg_partial_charge_dmso                         35
avg_atomic_fukui_minus                          35
avg_atomic_quadrupole_principal_invariant_3     35
avg_atomic_fukui_plus                           35
avg_partial_charge                              35
avg_atomic_dipole_norm                          35
avg_atomic_charge_dipole_interaction            35
avg_bond_stiffness                              35
avg_overlap_integral                            35
avg_bond_length                                 35
avg_atomic_dipole_dipole_interaction            35
avg_nuclear_repulsion                           35
avg_atomic_charge_quadrupole_interaction        35
avg_bond_energy                                177
dtype: int64

In [11]:
null_df = df[df.isnull().any(axis=1)].reset_index()

In [12]:
null_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 57 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   index                                        177 non-null    int64
 1   smiles                                       177 non-null    str
 2   energy                                       142 non-null    float64
 3   atomization_energy                           142 non-null    float64
 4   homo_lumo_gap                                142 non-null    float64
 5   ionization_energy                            142 non-null    float64
 6   electron_affinity                            142 non-null    float64
 7   chemical_potential                           142 non-null    float64
 8   molecular_dipole_norm                        142 non-null    float64
 9   molecular_quadrupole_principal_invariant_2   142 non-null    float64
 10  molecular_quadrupole_principal_invariant_3   142 non-null    float64
 11  molecular_polarizability_mean                142 non-null    float64
 12  molecular_polarizability_anisotropy          142 non-null    float64
 13  enthalpy                                     142 non-null    float64
 14  zero_point_energy                            142 non-null    float64
 15  radius_of_gyration                           142 non-null    float64
 16  molecular_volume                             142 non-null    float64
 17  sterimol_L                                   142 non-null    float64
 18  sterimol_Bmin                                138 non-null    float64
 19  sterimol_Bmax                                138 non-null    float64
 20  molecular_sasa                               142 non-null    float64
 21  solvation_energy_water                       142 non-null    float64
 22  solvation_energy_thf                         142 non-null    float64
 23  solvation_energy_cyclohexane                 142 non-null    float64
 24  solvation_energy_dmso                        142 non-null    float64
 25  gibbs_free_energy_300K                       142 non-null    float64
 26  entropy_300K                                 142 non-null    float64
 27  heat_capacity_300K                           142 non-null    float64
 28  ir_centroid_freq_1500                        142 non-null    float64
 29  ir_norm_intensity_1500                       142 non-null    float64
 30  ir_centroid_freq_1500_2750                   142 non-null    float64
 31  ir_norm_intensity_1500_2750                  142 non-null    float64
 32  ir_centroid_freq_2750_4000                   142 non-null    float64
 33  ir_norm_intensity_2750_4000                  142 non-null    float64
 34  avg_effective_coordination_number            142 non-null    float64
 35  avg_atomic_polarizability_mean               142 non-null    float64
 36  avg_partial_charge_water                     142 non-null    float64
 37  avg_percentage_buried_volume                 142 non-null    float64
 38  avg_atomic_polarizability_anisotropy         142 non-null    float64
 39  avg_atomic_sasa                              142 non-null    float64
 40  avg_partial_charge_thf                       142 non-null    float64
 41  avg_atomic_quadrupole_principal_invariant_2  142 non-null    float64
 42  avg_partial_charge_cyclohexane               142 non-null    float64
 43  avg_partial_charge_dmso                      142 non-null    float64
 44  avg_atomic_fukui_minus                       142 non-null    float64
 45  avg_atomic_quadrupole_principal_invariant_3  142 non-null    float64
 46  avg_atomic_fukui_plus                        142 non-null    float64
 47  avg_partial_charge                           142 non-null    float64
 48  avg_atomic_dipole_norm                       142 non-null    float64
 49  avg_atomic_charge_dipole_interaction         142 non-null    float64
 50  avg_bond_stiffness                           142 non-null    float64
 51  avg_overlap_integral                         142 non-null    float64
 52  avg_bond_length                              142 non-null    float64
 53  avg_atomic_dipole_dipole_interaction         142 non-null    float64
 54  avg_nuclear_repulsion                        142 non-null    float64
 55  avg_atomic_charge_quadrupole_interaction     142 non-null    float64
 56  avg_bond_energy                              0 non-null      float64
dtypes: float64(55), int64(1), str(1)
memory usage: 78.9 KB

In [13]:
null_df[null_df["sterimol_Bmax"].isna() & null_df["energy"].notna()]

,index,smiles,energy,atomization_energy,homo_lumo_gap,ionization_energy,electron_affinity,chemical_potential,molecular_dipole_norm,molecular_quadrupole_principal_invariant_2,...,avg_partial_charge,avg_atomic_dipole_norm,avg_atomic_charge_dipole_interaction,avg_bond_stiffness,avg_overlap_integral,avg_bond_length,avg_atomic_dipole_dipole_interaction,avg_nuclear_repulsion,avg_atomic_charge_quadrupole_interaction,avg_bond_energy
44,1266,[S:1]=[Fe:2],-6.290732,0.195666,0.009650,0.423603,0.178285,-0.298930,2.873166,-2.955365,...,1.000000e-10,0.558620,0.065998,0.503757,0.559439,3.735073,0.007325,58.937993,-0.007910,NaN
47,1308,[O:1]=[Mn:2],-6.779702,0.390915,0.047629,0.457364,0.153677,-0.296536,3.026655,-8.978168,...,0.000000e+00,1.303515,0.140346,0.861228,0.450179,2.790336,0.250665,37.929284,-0.042319,NaN
67,1645,[O:1]=[Co:2],-7.563763,0.286841,0.009911,0.492495,0.199619,-0.335602,2.494365,-0.764242,...,0.000000e+00,0.683334,0.121129,0.879061,0.461955,2.837714,0.018588,40.279705,-0.089018,NaN
175,8814,[O:1]=[Y:2],-5.217238,0.252253,0.047072,0.539219,0.156817,-0.349591,2.199255,-32.989183,...,-0.000000e+00,0.206345,0.029041,0.186508,0.346850,3.565589,-0.011236,46.304641,0.107557,NaN

In [22]:
output_files_numbers[1645]

2483

In [15]:
file_numbers = [output_files_numbers[idx] for idx in null_df["index"].to_list()]
file_numbers

[106,
 1083,
 1092,
 1106,
 1116,
 114,
 1167,
 1184,
 1198,
 1218,
 1245,
 1259,
 1272,
 1274,
 1276,
 1278,
 1280,
 1282,
 1286,
 1291,
 1292,
 1300,
 1305,
 1325,
 1333,
 1343,
 1344,
 1355,
 1396,
 1406,
 141,
 1515,
 1523,
 154,
 1572,
 1707,
 1807,
 188,
 1915,
 1925,
 1979,
 1993,
 2091,
 2131,
 2140,
 2146,
 2171,
 2179,
 2183,
 2185,
 2220,
 2299,
 2314,
 2369,
 2370,
 2371,
 2373,
 2377,
 2388,
 2390,
 2397,
 2434,
 2442,
 2443,
 2446,
 2464,
 247,
 2483,
 2501,
 2504,
 2510,
 2515,
 2531,
 2543,
 2550,
 2567,
 2577,
 2578,
 2591,
 2592,
 2593,
 2698,
 2702,
 2703,
 2704,
 2785,
 2786,
 290,
 2992,
 3039,
 3101,
 3168,
 3259,
 3263,
 3374,
 3377,
 346,
 3471,
 3570,
 3575,
 3612,
 3700,
 3825,
 3841,
 3897,
 3899,
 3903,
 3930,
 4324,
 4334,
 4347,
 4349,
 4350,
 449,
 456,
 4574,
 4705,
 4799,
 48,
 485,
 489,
 5084,
 5085,
 5127,
 5174,
 5200,
 5201,
 5473,
 5498,
 5574,
 5576,
 5634,
 5635,
 5787,
 5896,
 5898,
 5913,
 5923,
 5937,
 6072,
 6156,
 620,
 6297,
 636,
 645,
 6455,
 65,
 656,
 669,
 676,
 681,
 687,
 692,
 6955,
 736,
 7403,
 7434,
 7435,
 745,
 7465,
 7667,
 7669,
 769,
 7754,
 7843,
 7947,
 852,
 8597,
 8603,
 8731,
 8738,
 8740,
 8746,
 8777,
 882,
 979,
 99]

In [16]:
# null_df[null_df["index"]==158].info()

In [23]:
# for df in loader.stream_conformer_dataframe(OUTPUT_PATH / Path("internship_smiles2_114.json.gz")):
for df in loader.stream_conformer_dataframe(OUTPUT_PATH / Path("internship_smiles2_2483.json.gz")):
    tdf = df

# print(tdf.info())
tdf["sterimol_Bmax"]

0    2
Name: sterimol_Bmax, dtype: Int64

In [24]:
tdf[tdf.isnull().any(axis=1)].reset_index()

Empty DataFrame
Columns: [index, energy, atomization_energy, homo_lumo_gap, ionization_energy, electron_affinity, chemical_potential, molecular_dipole, molecular_dipole_norm, molecular_quadrupole, molecular_quadrupole_principal_invariant_2, molecular_quadrupole_principal_invariant_3, molecular_polarizability, molecular_polarizability_mean, molecular_polarizability_anisotropy, normal_modes, normal_mode_frequencies, infrared_intensity, enthalpy, gibbs_free_energy, entropy, zero_point_energy, radius_of_gyration, molecular_volume, sterimol_L, sterimol_Bmin, sterimol_Bmax, molecular_sasa, heat_capacity, solvation_energy_water, solvation_energy_thf, solvation_energy_cyclohexane, solvation_energy_dmso, effective_coordination_number, partial_charge, atomic_fukui_minus, atomic_fukui_plus, atomic_dipole, atomic_dipole_norm, atomic_quadrupole, atomic_quadrupole_principal_invariant_2, atomic_quadrupole_principal_invariant_3, atomic_polarizability, atomic_polarizability_mean, atomic_polarizability_anisotropy, percentage_buried_volume, atomic_sasa, partial_charge_water, partial_charge_thf, partial_charge_cyclohexane, partial_charge_dmso, bond_energy, bond_length, bond_stiffness, overlap_integral, nuclear_repulsion, atomic_charge_dipole_interaction, atomic_charge_quadrupole_interaction, atomic_dipole_dipole_interaction, original_smiles, output_smiles]
Index: []

[0 rows x 61 columns]

In [25]:
engineer = QFPFeatureEngineer(300.0)
cleaned_tdf = engineer.clean_features(tdf)
aggregator = ConformerAggregator()
processed_tdf = aggregator.thermal_average(cleaned_tdf)

processed_tdf

C:\Users\thibo\OneDrive\Bureaublad\Enhancing-aqueous-solubility-prediction-models\ml_enhance\qfp_processing\feature_engineering.py:156: RuntimeWarning: Mean of empty slice
  return np.array([x[2] for x in interaction_feature]).mean()
c:\Users\thibo\OneDrive\Bureaublad\Enhancing-aqueous-solubility-prediction-models\.venv\Lib\site-packages\numpy\_core\_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

smiles                                         [O:1]=[Co:2]
energy                                            -7.563763
atomization_energy                                 0.286841
homo_lumo_gap                                      0.009911
ionization_energy                                  0.492495
electron_affinity                                  0.199619
chemical_potential                                -0.335602
molecular_dipole_norm                              2.494365
molecular_quadrupole_principal_invariant_2        -0.764242
molecular_quadrupole_principal_invariant_3        -0.257155
molecular_polarizability_mean                    -41.003243
molecular_polarizability_anisotropy              592.809366
enthalpy                                          -6.190301
zero_point_energy                                  1.373461
radius_of_gyration                                 0.504338
molecular_volume                                 266.626638
sterimol_L                                         5.021654
sterimol_Bmin                                           2.0
sterimol_Bmax                                           2.0
molecular_sasa                                   283.513034
solvation_energy_water                            -0.031634
solvation_energy_thf                              -0.027032
solvation_energy_cyclohexane                      -0.014617
solvation_energy_dmso                             -0.031302
gibbs_free_energy_300K                           -22.321846
entropy_300K                                       0.053772
heat_capacity_300K                                  0.00502
ir_centroid_freq_1500                            960.748987
ir_norm_intensity_1500                                  1.0
ir_centroid_freq_1500_2750                              0.0
ir_norm_intensity_1500_2750                             0.0
ir_centroid_freq_2750_4000                              0.0
ir_norm_intensity_2750_4000                             0.0
avg_partial_charge                                      0.0
avg_atomic_quadrupole_principal_invariant_2       -0.575545
avg_partial_charge_cyclohexane                          0.0
avg_atomic_polarizability_mean                   -18.042163
avg_partial_charge_thf                                  0.0
avg_effective_coordination_number                  0.988715
avg_atomic_fukui_plus                                  -0.5
avg_percentage_buried_volume                      23.999434
avg_atomic_polarizability_anisotropy             880.284856
avg_atomic_sasa                                  141.756517
avg_partial_charge_dmso                                 0.0
avg_atomic_quadrupole_principal_invariant_3       -0.222511
avg_atomic_dipole_norm                             0.683334
avg_atomic_fukui_minus                                 -0.5
avg_partial_charge_water                                0.0
avg_atomic_charge_quadrupole_interaction          -0.089018
avg_atomic_charge_dipole_interaction               0.121129
avg_bond_stiffness                                 0.879061
avg_bond_energy                                         NaN
avg_nuclear_repulsion                             40.279705
avg_overlap_integral                               0.461955
avg_atomic_dipole_dipole_interaction               0.018588
avg_bond_length                                    2.837714
dtype: object

In file 114, has empty bond_energy which leads to something wrong in the engineer

In [20]:
for t in loader.stream_conformer_dataframe(OUTPUT_PATH / "internship_smiles2_0.json.gz"):
    print(t["gibbs_free_energy"])

0    [[200.0, 42.6861593912284], [300.0, 30.8223823...
Name: gibbs_free_energy, dtype: object